train_partseg.py:37: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)

**************************

[workers]: 4

[num_points]: 2048

[num_classes]: 50

[batch_size]: 28

[base_lr]: 0.001

[lr_clip]: 1e-05

[lr_decay]: 0.5

[decay_step]: 21

[epochs]: 200

[weight_decay]: 0

[bn_momentum]: 0.9

[bnm_clip]: 0.01

[bn_decay]: 0.5

[evaluate]: 1

[val_freq_epoch]: 0.7

[print_freq_iter]: 20

[input_channels]: 0

[relation_prior]: 1

[checkpoint]: 

[save_path]: seg

[data_root]: /media/disk3/pyy/Relation-Shape-CNN/shapenetcore_partanno_segmentation_benchmark_v0_normal

**************************

/media/disk3/pyy/Relation-Shape-CNN/shapenetcore_partanno_segmentation_benchmark_v0_normal
Traceback (most recent call last):
  File "train_partseg.py", line 172, in <module>
    main()
  File "train_partseg.py", line 58, in main
    train_dataset = ModelNet40Cls(num_points = args.num_points, root = args.data_root, transforms=train_transforms)
  File "/media/disk3/pyy/RSCNN_Pytorch1.0/data/ModelNet40Loader.py", line 44, in __init__
    os.path.join(self.data_dir, 'train_files.txt'))
  File "/media/disk3/pyy/RSCNN_Pytorch1.0/data/ModelNet40Loader.py", line 10, in _get_data_files
    with open(list_filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/media/disk3/pyy/Relation-Shape-CNN/shapenetcore_partanno_segmentation_benchmark_v0_normal/train_files.txt'
